# Generated by Django 4.1.2 on 2022-10-07 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('advocates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='advocate_years_exp',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.companyprofile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='long_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
